name: Build-and-deploy-to-gke

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{secrets.GCP_PROJECT}}
  GKE_CLUSTER: ${{secrets.GKE_CLUSTER}}
  GKE_PROJECT: ${{secrets.GCP_PROJECT}}
  GKE_ZONE: us-central1-c
  IMAGE: gcr.io/${{secrets.GCP_PROJECT}}/rakeshapp13

jobs: 
  setup-build-publish-deploy:
    name: setup, build, publish, deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{secrets.GCP_SERVICE_ACCOUNT_KEY}}'


    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{secrets.GCP_PROJECT}}
        servic_account_key: ${{secrets.GCP_SERVICE_ACCOUNT_KEY}}
        export_defaulr_credentials: true

    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-


        gcloud container clusters get-credentials shivam123 --zone us-central1-c --project rb-munish-playground

    - name: Build
      run: |-
        docker build . -t $IMAGE
        echo "Image Build Done"        

    - name: Publish
      run: |-
        docker push $IMAGE
        echo "Image publish to docker done" 
    

    - name: Deploy
      run: |-
        kubectl apply -f deployment.yaml
        echo "Application Deployment Done" 